create table public.teacher
(
    id   bigint generated by default as identity (start with 100)
        primary key,
    name varchar(100) not null
);

alter table public.teacher
    owner to ababab;

create table public.course
(
    id         bigint generated by default as identity (start with 100)
        primary key,
    name       varchar(50) not null
        constraint uk_course_1
            unique,
    teacher_id bigint      not null
        constraint fk_teacher_1
            references public.teacher
);

alter table public.course
    owner to ababab;

create table public.student
(
    id   bigint generated by default as identity (start with 100)
        primary key,
    name varchar(100) not null
);

alter table public.student
    owner to ababab;

create table public.student_course
(
    student_id bigint not null
        constraint fk_student_course_2
            references public.student,
    course_id  bigint not null
        constraint fk_student_source_1
            references public.course,
    primary key (student_id, course_id)
);

alter table public.student_course
    owner to ababab;

create table public.author
(
    id    bigint       not null
        primary key,
    name  varchar(255) not null,
    email varchar(255) not null
        unique
);

alter table public.author
    owner to ababab;

create table public.commenter
(
    id       bigint       not null
        primary key,
    username varchar(255) not null
        unique,
    password varchar(255) not null
);

alter table public.commenter
    owner to ababab;

create table public.post
(
    id        bigint       not null
        primary key,
    title     varchar(255) not null,
    content   varchar(255) not null,
    author_id bigint
        references public.author
);

alter table public.post
    owner to ababab;

create table public.post_author
(
    post_id   bigint not null
        references public.post,
    author_id bigint not null
        references public.author,
    primary key (post_id, author_id)
);

alter table public.post_author
    owner to ababab;

create table public.comment
(
    id           bigint       not null
        primary key,
    content      varchar(255) not null,
    post_id      bigint
        references public.post,
    commenter_id bigint
        references public.commenter
);

alter table public.comment
    owner to ababab;

create table public.appuser
(
    id       bigint       not null
        primary key,
    username varchar(255) not null,
    password varchar(255) not null
);

alter table public.appuser
    owner to ababab;

create table public.profile
(
    id         bigint not null
        primary key,
    bio        varchar(255),
    appuser_id bigint
        unique
        references public.appuser
);

alter table public.profile
    owner to ababab;

create table public.blog
(
    id          bigint       not null
        primary key,
    name        varchar(255) not null,
    description varchar(255)
);

alter table public.blog
    owner to ababab;

create table public.article
(
    id      bigint       not null
        primary key,
    title   varchar(255) not null,
    content varchar(255) not null,
    blog_id bigint
        references public.blog
);

alter table public.article
    owner to ababab;

create table public.writer
(
    id   bigint       not null
        primary key,
    name varchar(255) not null
);

alter table public.writer
    owner to ababab;

create table public.book
(
    id    bigint       not null
        primary key,
    title varchar(255) not null
);

alter table public.book
    owner to ababab;

create table public.writer_book
(
    writer_id bigint not null
        references public.writer,
    book_id   bigint not null
        references public.book,
    primary key (writer_id, book_id)
);

alter table public.writer_book
    owner to ababab;

