#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: DEBUG
#    jdbc.sqlonly: DEBUG
spring:
  jpa:
    format_sql: true
    use_sql_comments: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://127.0.0.1:5432/jpa_demo}
    username: ${DATABASE_USERNAME:ababab}
    password: ${DATABASE_PASSWORD:bababa}